### ISSUE TITLE
DOUBT REGARDING WINDOWS INSTALLATION

### ISSUE THREAD

**Issue by reachaadrika** [internetarchive/wari#657]
The developers notes and the installation notes , that are provided , are they linux friendly only or I can also use windows ?

**Comment by dpriskorn** [comment]
Gunicorn is Linux only. The rest is pure python so any other python http server should do.

**Comment by dpriskorn** [comment]
I updated the developer notes. I'm closing this, feel free to reopen/open a new issue if you have any questions.
