### ISSUE TITLE
/reference endpoint does not include wikitext or templates in json, whereas it used to 

### ISSUE THREAD

**Issue by mojomonger** [internetarchive/wari#700]
fetching an "old" reference, i.e., one that was requeste in the recent two weeks and therefore had a cached version of the reference, provides the wikitext and templates properties n the json.
The recent "new" references, ones that are generated with the current WARI api, seem to not include the wikitext of templates entries. click on the links to see the returned data.
 
"new" Jeff Beck reference:
https://archive.org/services/context/wari/v2/statistics/reference/13c980b6

"old" Easter Island example reference:
https://archive.org/services/context/wari/v2/statistics/reference/a300ab66

**Comment by dpriskorn** [comment]
I found the cause of this bug. It was related to https://docs.python.org/3/library/copy.html.
I created a test and with deepcopy it now pass.
