### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by harej** [internetarchive/wari#738]
I expect Python module dependencies to be documented in a requirements.txt file so that I can install them when deploying to another server.

**Comment by harej** [comment]
I see you use another tool called poetry for dependency management, which itself is installed with pip. What does poetry bring to the table that pip doesn't?

**Comment by dpriskorn** [comment]
It brings a lot of features. Update of dependencies, integration with GitHub dependency checking, release Management, etc.
